/*
 *
 * Chat constants
 *
 */

export const DEFAULT_ACTION = 'app/Chat/DEFAULT_ACTION';
export const TOGGLE_DRAWER_ACTION = 'app/Chat/TOGGLE_DRAWER_ACTION';
export const TOGGLE_DARK_ACTION = 'app/Chat/TOGGLE_DARK_ACTION';
export const USER_ENTER_ACTION = 'app/Chat/USER_ENTER_ACTION';
export const UPDATE_USERNAME_ACTION = 'app/Chat/UPDATE_USERNAME_ACTION';
export const UPDATE_PASSWORD_ACTION = 'app/Chat/UPDATE_PASSWORD_ACTION';
export const TOGGLE_PASSW_VISIBILITY_ACTION =
  'app/Chat/TOGGLE_PASSW_VISIBILITY_ACTION';
export const USER_LOGOUT_ACTION = 'app/Chat/USER_LOGOUT_ACTION';
export const SEND_TEXT_ACTION = 'app/Chat/SEND_TEXT_ACTION';
export const UPDATE_MESSAGE_ACTION = 'app/Chat/UPDATE_MESSAGE_ACTION';
